language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements-dev.txt
  - pip install .
  - pip install coveralls
env:
  - VERBOSE_TESTING=0 INIT_SPARK_ON_IMPORT=1
script:
  - coverage run -p -m tests
after_success:
  - coverage combine
  - coverage report
  - coveralls
  - pylint --errors-only sparklanes
notifications:
  email:
    recipients:
      - build@ksbg.io